### ISSUE TITLE
Is there a nemo stability version with rocksdb version higher than 5.0?

### ISSUE THREAD

**Issue by loadwiki** [Qihoo360/nemo#11]
Rocksdb version in memo release  v0.1.2 is low.
It doesn't support rocksdb ingest,ssttabelwriter api.
So in v0.1.2 it is hard to dump or ingest raw sst table file.
Is there a stabilize  nemo version with rocksdb version higher than 5.0?

**Comment by KernelMaker** [comment]
you can use master branch, it supports rocksdb 5.0.1 and latest
