### ISSUE TITLE
no method to release snapshot when use nemo iterator

### ISSUE THREAD

**Issue by loadwiki** [Qihoo360/nemo#13]
There is no api to release snapshot of rocksdb instance when use nemo iterator(HIterator KIterator  ...)with snapshot.

**Comment by KernelMaker** [comment]
HIterator, KIterator should not be used by users, they were just called from other public functions like scan, keys...，you can use them instead.

**Comment by loadwiki** [comment]
In case of function Nemo::SPop, SSCan creates a iterator with a snapshot. However, the snapshot is not released after the iterator has been deleted.

**Comment by loadwiki** [comment]
In function SRandMember,the issue repeates.

**Comment by KernelMaker** [comment]
1. spop, srandmember would destroy the snapshot at scope exit
2. sscan create a SIterator without snapshot, so it doesn't have to release any snapshot.

**Comment by loadwiki** [comment]
Sorry, my mistake.
I remove the release snapshot statement after i add some release snapshot
ops in Iterator desturcture.
This is done because some scan api exported to 3party.
I forgot my remove ops.

2017-05-24 14:58 GMT+08:00 SongZhao <notifications@github.com>:
